apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
        version: "v1.1"
  template:
    metadata:
      labels:
        app: webui
        version: "v1.1"
    spec:
      containers:
        - name: webui
          image: webui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
